# Generated by Django 5.2 on 2025-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                ("surname", models.CharField(max_length=255, verbose_name="Surname")),
                (
                    "attendance_count",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Attendence Count"
                    ),
                ),
            ],
        ),
    ]
