# Generated by Django 5.2 on 2025-04-22 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atTracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="attendance_count",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0, "Min attendence is 0")
                ],
                verbose_name="Attendence Count",
            ),
        ),
    ]
